export enum MqMessageType {
  USER_JOINED = 'USER_JOINED',
  USER_LEFT = 'USER_LEFT',
  VIEWER_JOINED = 'VIEWER_JOINED',
  VIEWER_LEFT = 'VIEWER_LEFT',
  GREEN_ROOM_USER_JOINED = 'GREEN_ROOM_USER_JOINED',
  GREEN_ROOM_USER_LEFT = 'GREEN_ROOM_USER_LEFT',
  SESSION_CLOSED = 'SESSION_CLOSED',
  USER_BLOCKED = 'USER_BLOCKED',
}
